"""Initial

Revision ID: 76d144c27eda
Revises: 
Create Date: 2023-11-23 15:08:37.812330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d144c27eda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('addresses',
    sa.Column('postcode', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('postcode')
    )
    op.create_index('ix_addresses_postcode_c_locale', 'addresses', ['postcode'], unique=False, postgresql_ops={'postcode': 'varchar_pattern_ops'})
    op.create_table('aliases',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliases')
    op.drop_index('ix_addresses_postcode_c_locale', table_name='addresses', postgresql_ops={'postcode': 'varchar_pattern_ops'})
    op.drop_table('addresses')
    op.drop_table('regions')
    # ### end Alembic commands ###
