name: egrul_fts_api Workflow

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install region_finder_ru-0.0.1-py3-none-any.whl
        pip install -r requirements.txt

    - name: Testing with flake8
      run: python -m flake8

    - name: Testing with Pytest
      run: python -m pytest
